### ISSUE TITLE
README is lacking

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-content-scanner-python#21]
Could you give this repo a readme, to give people some basic info on what it is?

(possibly also a CONTRIBUTING)

**Comment by babolivier** [comment]
I thought I had an issue already open about it but apparently I forgot? I wanted to wait till the code base is migrated because otherwise half of the readme would be referencing things that don't exist yet and give a false impression that the project is ready to be used. But I can also just shove a big warning on top of it to tell people not to use it yet and push it otherwise as is.
